apiVersion: v1
kind: Service
metadata:
  name: app-green
spec:
  type: LoadBalancer
  ports:
  - port: 8081

  # Note here that we match both the app and the version
  selector:
    app: app
    version: v2.0.0 
